---
- name: kube-proxy
  box: devopsbox/ubuntu-20.04
  hostname: kube-proxy
  ipaddress: 192.168.230.150
  memory: 1024
  cpus: 1
  provision: provision/ansible/kube-proxy.yaml

- name: kube-master1
  box: devopsbox/ubuntu-20.04
  hostname: kube-master1
  ipaddress: 192.168.230.151
  memory: 2560
  cpus: 2
  provision: provision/ansible/kube-master1.yaml

- name: kube-master2
  box: devopsbox/ubuntu-20.04
  hostname: kube-master2
  ipaddress: 192.168.230.152
  memory: 2560
  cpus: 2
  provision: provision/ansible/kube-master2.yaml

- name: kube-master3
  box: devopsbox/ubuntu-20.04
  hostname: kube-master3
  ipaddress: 192.168.230.153
  memory: 2560
  cpus: 2
  provision: provision/ansible/kube-master3.yaml

- name: kube-worker1
  box: devopsbox/ubuntu-20.04
  hostname: kube-worker1
  ipaddress: 192.168.230.154
  memory: 1024
  cpus: 2
  provision: provision/ansible/kube-master1.yaml
