---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: infra
spec:
  addresses:
  - 192.168.230.201-192.168.230.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
